<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0-windows</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<IsPackable>false</IsPackable>
		<IsTestProject>true</IsTestProject>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.3.0" />
		<PackageReference Include="NUnit" Version="4.4.0" />
		<PackageReference Include="NUnit3TestAdapter" Version="5.2.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\ShoppingCart.Domain\ShoppingCart.Domain.csproj" />
		<ProjectReference Include="..\ShoppingCart.Application\ShoppingCart.Application.csproj" />
		<ProjectReference Include="..\ShoppingCart.Infrastructure\ShoppingCart.Infrastructure.csproj" />
		<ProjectReference Include="..\ShoppingCart\ShoppingCart.WPF.csproj" />
	</ItemGroup>

</Project>